- src/components/FilterAndCategory.tsx
- src/pages/About/About.tsx
- src/pages/About/AboutDetail.tsx
- tailwind.config.js
- yarn.lock
_Renaming color classname for about_
-   _Using the color classname from tailwind config_
-   _Add a new color 'DarkOrange' to config_
-   _Renamed duplicated LightBrown to MediumBrown_
not needed
not needed
> [Refactor] Renaming color classname for about

- src/pages/Homepage/Homepage.tsx
- src/pages/Partnerpage/PartnerPage.tsx
_Add sponsor and medpar section_
-   _Using grid to display the image_
-   _Using the sponsor & medpar element from Partner page_
- _Added page title ligature_
none
_For FE in mobile and web_
> [Task] homepage sponsor

- src/pages/About/About.tsx
_add base layout components_
-   _Added base layout components for about page_
_none_
> [Task] about add components

- src/pages/About/About.tsx
- src/pages/Detailpage/Detailpage.tsx
- src/pages/Detailpage/Render.tsx
- src/pages/Partnerpage/PartnerPage.tsx
_add header footer for partner and detail page_
-   _add base layout_
-   _fix bug render subheading_
_none_
> [Task] add header footer for partner and detail post page

- src/components/BlogPost.tsx
- src/components/Pagination.tsx
- src/layout/BaseLayout.tsx
- src/pages/About/About.tsx
- src/pages/About/AboutDetail.tsx
- src/pages/Homepage/Homepage.tsx
- src/pages/Partnerpage/PartnerPage.tsx
Fix some errors in the browser console
- Fix errors in console, mostly because "each child in a list should have a unique 'key' prop"
- Open some pages in website
- Check console whether there are some errors or not
> [Task] Fix Error in Console

- src/util/renderHTMLContent.ts
##Task
_Fix import_
-   _Fix import from renderHTMLContent.ts_
More on:
https://github.com/taoqf/node-html-parser/issues/149
https://github.com/taoqf/node-html-parser/issues/139
-   [x] _Visit post page on build files_
> [Task] fix import

- src/pages/Detailpage/Render.tsx
- src/types/interface.ts
- src/util/util.ts
_Fix figure such as image, video, youtube, twitter, spotify, gallery_
-   _Add figure attribute interface_
-   _Add attribute parser_
-   _Add caption and alt for image
_
_Add figure element_
> [Fix] refactor parse for figure

- src/pages/About/AboutDetail.tsx
- src/pages/Detailpage/Detailpage.tsx
- src/pages/Detailpage/Render.tsx
_responsive and feature image_
-   _Add renderCaption_
-   _Use 500px for max feature image height_
-   _Fix about page mobile overlap_
-   _Fix feature image overlap container_
_none_
> [Task] responsive and feature image

- src/components/BlogPost.tsx
- src/pages/About/About.tsx
- src/pages/Detailpage/Detailpage.tsx
- src/pages/Detailpage/RelatedPosts.tsx
- src/pages/Partnerpage/PartnerPage.tsx
- src/types/constant.ts
_fix responsive_
-   _Responsive post card_
-   _Responsive related post_
-   _Fix about post content overlap in certain screen height_
-   _Shorter trimmed text for related post_
-   _Add max height 500px to default feature image_
_just check the responsiveness of everything_
> [Task] fix responsive post card

- src/components/BlogPost.tsx
- src/components/FilterAndCategory.tsx
- src/components/Pagination.tsx
- src/pages/Searchpage/Searchpage.tsx
- src/service/ghostAPI.ts
- src/types/interface.ts
_Improve tag filtering_
-   _Improve tag filtering_
-   [ ] _Will start at the homepage_
-   [ ] _Filter on any blog post, will go to search page with filtered tag_
> [Task] Improve tag filtering

- src/components/FilterAndCategory.tsx
- src/components/Navbar.tsx
- src/pages/About/About.tsx
- src/pages/About/AboutDetail.tsx
- src/pages/Detailpage/Detailpage.tsx
- src/pages/ErrorPage.tsx
- src/pages/Homepage/Homepage.tsx
- src/pages/Partnerpage/PartnerPage.tsx
- src/pages/Searchpage/Searchpage.tsx
- src/pages/TreasureHuntPage/TreasureHuntPage.tsx
- src/types/constant.ts
Adding document title to each page so that it makes more professional
1. Change logo in about page
2. Add document title on each page
-   [x]  User load the page and should see Home - OSKM ITB 2022
-   [x]  User check for all pages and it should display differently
> [Task] Adding document title on each page

- src/components/BlogPost.tsx
Add minimum height on content list description
- Add minimum height on content desctiption
- Open the website
- Set browser width to mobile size
> [Task] Adding Min Height on Content Description

- src/pages/TreasureHuntPage/ToBeAnnounced.tsx
- src/pages/TreasureHuntPage/TreasureHuntPage.tsx
- src/pages/TreasureHuntPage/TreasureHuntPageUnit.tsx
- src/routing.ts
Create To Be Announced
-   add new page "to be announced" for defile unit
-   add loading page when open list of unit
-   [x] click the defile menu before 19 august
-   [x] it will go to the "tobeannounced" page
> add to be announced

- src/pages/TreasureHuntPage/TreasureHuntPage.tsx
- Defile unit quiz sebelum ke main defile unit
- Bikinnya di satu page, jadi pake useState, kalo password bener statenya berubah
> [Story] add defile unit quiz before enter

- src/pages/Homepage/Homepage.tsx
- logo announcement di homepage undraggable
> [Task] make image undraggable

- src/components/Rumpun.tsx
- src/pages/Partnerpage/PartnersList.ts
- src/pages/TreasureHuntPage/TreasureHuntPage.tsx
- src/types/constant.ts
Update Defile Page
Added subheading
Added rounded squares
Updated font
> updated defile

- src/components/Carousel.tsx
- src/pages/Partnerpage/PartnersList.ts
_benerin carousel bikin arrownya di luar trs jarak antar navigation boxnya dirapihin_
mobile normal length of item:
mobile full item (9):
desktop:
> fix: revamp carousel

- src/components/VistockPartner.tsx
- src/components/VistockRumpum.tsx
- src/index.css
- src/pages/Partnerpage/PartnerPage.tsx
- src/pages/Partnerpage/PartnersList.ts
- src/pages/TreasureHuntPage/TreasureHuntPageUnit.tsx
_Create Homepage_
-   _Added New Endpoint_
-   _add config in tailwind_
-   [ ] _Will start at the homepage_
-   [ ] _Click home then routes will go to the page_
_For FE in mobile and web_
_for BE screenrecord/gif/ss req and response and make sure it's working_
-   Don't Forget to add prefix to PR [Story] Create homepage / [Task] Enhancement
-   Adding label might helpful
-   Fill the template :D
-   Request review to your friend :D
-   Change to merge and squash commit to make more cleaner
> style: Add vistock

- src/pages/TreasureHuntPage/TreasureHuntPage.tsx
- src/types/constant.ts
- Vistock buat Defile Selamat Datang
- Input password sekali
> [Story] add vistock and persist password status to localStorage

- src/pages/Detailpage/Detailpage.tsx
_fix related defile_
-   _add checking related tags before continue rendering_
-   _use excludeTags const_
http://localhost:3000/post/unit-abc for post with defile tags
http://localhost:3000/post/ini-post-sponsor for non defile tags posts
> fix related defile

- index.html
- src/pages/About/About.tsx
- src/pages/Detailpage/Detailpage.tsx
- src/pages/ErrorPage.tsx
- src/pages/Homepage/Homepage.tsx
- src/pages/Partnerpage/PartnerPage.tsx
- src/pages/Searchpage/Searchpage.tsx
_Create Homepage_
-   _Added New Endpoint_
-   _add config in tailwind_
-   [ ] _Will start at the homepage_
-   [ ] _Click home then routes will go to the page_
_For FE in mobile and web_
_for BE screenrecord/gif/ss req and response and make sure it's working_
-   Don't Forget to add prefix to PR [Story] Create homepage / [Task] Enhancement
-   Adding label might helpful
-   Fill the template :D
-   Request review to your friend :D
-   Change to merge and squash commit to make more cleaner
> style: capitalize Deva

- src/components/VistockPartner.tsx
- src/index.css
Fixed partner page footer bug
height container dari partner-bg nya kelebihan
> fixed partner page footer bug

- src/layout/BaseLayout.tsx
Updating footer
Buat div di footer jadi sejajar container di sponsor
> repositioned footer 

- src/pages/Error/EmptyPost.tsx
- src/pages/Error/PageNotFound.tsx
- src/pages/Error/PostNotFound.tsx
- src/pages/Error/ServerError.tsx
_Create Homepage_
-   _Added New Endpoint_
-   _add config in tailwind_
-   [ ] _Will start at the homepage_
-   [ ] _Click home then routes will go to the page_
_For FE in mobile and web_
_for BE screenrecord/gif/ss req and response and make sure it's working_
-   Don't Forget to add prefix to PR [Story] Create homepage / [Task] Enhancement
-   Adding label might helpful
-   Fill the template :D
-   Request review to your friend :D
-   Change to merge and squash commit to make more cleaner
> style: responsive error

- src/components/BlogPost.tsx
- src/pages/Searchpage/Searchpage.tsx
- src/routing.ts
- src/types/constant.ts
Updated layout for search page
- Bikin filter jadi di atas
- Defined width buat baris
- Trim text by chakra
> updated search page layout

- src/components/BlogPost.tsx
- src/pages/Detailpage/RelatedPosts.tsx
_Create Homepage_
-   _Fix blog card_
> [Task] Fix blog card
